# Generated by Django 4.2.6 on 2024-03-25 19:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=100, null=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(null=False, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
