# Generated by Django 4.2.6 on 2024-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_username_customuser_fullname_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_description',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_links',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
