# Generated by Django 4.2.6 on 2024-03-29 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_skill_employee_experience_skillproficiency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(through='User.SkillProficiency', to='User.skill'),
        ),
        migrations.CreateModel(
            name='LanguageFluency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluency', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.employee')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.language')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.ManyToManyField(through='User.LanguageFluency', to='User.language'),
        ),
    ]
