# Generated by Django 4.2.6 on 2024-03-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_language_alter_employee_skills_languagefluency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(to='User.skill'),
        ),
        migrations.DeleteModel(
            name='SkillProficiency',
        ),
    ]
