# Generated by Django 4.2.6 on 2024-03-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_employee_skills_delete_skillproficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
