# Generated by Django 4.2.6 on 2024-04-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_skill_employee_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='availability',
            field=models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
