# Generated by Django 4.2.6 on 2024-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_employee_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
