# Generated by Django 4.2.6 on 2024-04-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='languages',
        ),
        migrations.DeleteModel(
            name='LanguageFluency',
        ),
    ]
