# Generated by Django 4.2.6 on 2024-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_remove_employee_languages_delete_languagefluency'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.ManyToManyField(to='User.language'),
        ),
    ]
