# Generated by Django 4.2.6 on 2024-04-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_alter_customuser_password_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='profile_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
