# Generated by Django 4.2.6 on 2024-04-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
